### ISSUE TITLE
Option Submenus

### ISSUE THREAD

**Issue by RintaDev5792** [OceanUwU/battlebot#1]
Add submenus for options to make more space for future things as so:
### Board
- AP distribution interval
- board width/height
- board drops e.g. Hearts, batteries, range, portal, black holes, #2 
### Players
- Starting hp, range, and ap
- other miscellaneous player abilities like "allow moving diagonal" and "allow pushing" (that whole section)
- #3

**Comment by OceanUwU** [comment]
![image](https://github.com/OceanUwU/battlebot/assets/29258858/dbb273f6-3222-4a74-8926-3127569dfca7)
