### ISSUE TITLE
Boards not working when higher than they are wide

### ISSUE THREAD

**Issue by RintaDev5792** [OceanUwU/battlebot#6]
They break idk what you want me to say
It only shows the letters and stuff on the top half of the board
You saw it

**Comment by OceanUwU** [comment]
![image](https://github.com/OceanUwU/battlebot/assets/29258858/de1a3f15-58fe-4bd4-9732-4ac24f285406)

**Comment by OceanUwU** [comment]
https://github.com/OceanUwU/battlebot/blob/22f4525c9761a10404be1ebcf4fe417c3f7ee64e/models/game/render.js#L45-L46
